### ISSUE TITLE
Hey dood

### ISSUE THREAD

**Issue by HatmanStack** [1ucky40nc3/easy_mpt#1]
Didn't take the time to dig in but on colab I'm getting a weird error "2023-05-28 22:47:44.286686: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT" after the 
`!python ../examples/mpt/convert-h5-to-ggml.py /content/models/mpt-7b-instruct 0`

This was after using wget to get the hugging face .bin part 01 and 02 instead of using git lfs smudge. Maybe that made a difference I dunno, maybe you don't care? luls...hope you are well.

**Comment by 1ucky40nc3** [comment]
Great to meet you again! Hope you are doing well!
Which Colab notebook did you use? I currently provide two Colab notebooks:

- One that only uses ggml [run_mpt_with_ggml.ipynb](https://github.com/1ucky40nc3/easy_mpt/blob/main/examples/notebooks/run_mpt_with_ggml.ipynb)
- One that loads the ggml model with ctransformers [run_mpt_with_ctransformers.ipynb](https://github.com/1ucky40nc3/easy_mpt/blob/main/examples/notebooks/run_mpt_with_ctransformers.ipynb)

Note: I also use the bigger Colab instances with 50 GB of RAM. Maybe this helps.

**Comment by HatmanStack** [comment]
It looks like the same message in both notebooks if you're interested...looks cool ***Care for Mudslides***:

`# @title Download the `mosaicml/mpt-7b-instruct` PLM
!mkdir -p /content/models
%cd /content/models
!git clone https://huggingface.co/mosaicml/mpt-7b-instruct`

`/content/models
Cloning into 'mpt-7b-instruct'...
remote: Enumerating objects: 106, done.
remote: Counting objects: 100% (106/106), done.
remote: Compressing objects: 100% (105/105), done.
remote: Total 106 (delta 54), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (106/106), 633.27 KiB | 3.37 MiB/s, done.
Resolving deltas: 100% (54/54), done.
Filtering content: 100% (2/2), 4.38 GiB | 11.07 MiB/s, done.
Encountered 1 file(s) that may not have been copied correctly on Windows:
	pytorch_model-00001-of-00002.bin

See: `git lfs help smudge` for more details.`

`# @title Convert the PLM into the ggml Format
%cd /content/ggml/build
!python ../examples/mpt/convert-h5-to-ggml.py /content/models/mpt-7b-instruct 0`

`/content/ggml/build
2023-06-06 19:17:12.525909: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
You are using config.init_device='cpu', but you can also use config.init_device="meta" with Composer + FSDP for fast initialization.
Loading checkpoint shards:   0% 0/2 [00:00<?, ?it/s]`
